### ISSUE TITLE
About 'lycon' module

### ISSUE THREAD

**Issue by Young-Zzz** [swz30/CycleISP#17]
Hi,when I run the 'test_dnd_rgb.py',If I didn't set the Parameter:'--save images',I can ran the code.
However,if I set the Parameter,I met the error:
```
Traceback (most recent call last):
  File "/workspace/Cycle/test_dnd_rgb.py", line 66, in <module>
    lycon.save(args.result_dir + 'png/'+ filenames[batch][:-4] + '.png', denoised_img)
  File "/opt/conda/lib/python3.7/site-packages/lycon/core.py", line 24, in save
    _lycon.save(path, image, options)
SystemError: <built-in function save> returned a result with an error set
```
Can u tell me why? Is the error of the 'lycon' version?But I only can pip install the version==0.2.0,the other version can't be pip install.

**Comment by eezhang123** [comment]
ucan use cv2 instead lycon
